--------------------------------------------------------
--  File created - Saturday-April-22-2023   
--------------------------------------------------------
DROP SEQUENCE "MOHAMMAD"."PROUCT_ID_SEQUENCE";
DROP TABLE "MOHAMMAD"."PRODUCT" cascade constraints;
DROP TABLE "MOHAMMAD"."USER_TABLE" cascade constraints;
DROP TABLE "MOHAMMAD"."WORKERS" cascade constraints;
DROP TABLE "MOHAMMAD"."USER_TABLE" cascade constraints;
DROP TABLE "MOHAMMAD"."PRODUCT" cascade constraints;
DROP TABLE "MOHAMMAD"."WORKERS" cascade constraints;
--------------------------------------------------------
--  DDL for Sequence PROUCT_ID_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "MOHAMMAD"."PROUCT_ID_SEQUENCE"  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 45 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "MOHAMMAD"."PRODUCT" 
   (	"PRODUCTID" NUMBER DEFAULT "MOHAMMAD"."PROUCT_ID_SEQUENCE"."NEXTVAL", 
	"PRODUCTNAME" VARCHAR2(20 BYTE), 
	"PRODUCTAREA" VARCHAR2(20 BYTE), 
	"QUANTITY" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(30 BYTE), 
	"PHONENUBMER" VARCHAR2(12 BYTE), 
	"USE_FLAG" VARCHAR2(5 BYTE), 
	"CLOTH_TYPE" VARCHAR2(10 BYTE), 
	"WELL_CLEANED" VARCHAR2(5 BYTE), 
	"CUSTOMER_EMAIL" VARCHAR2(30 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"PRICE" FLOAT(126), 
	"EMAIL_FLAG" VARCHAR2(10 BYTE), 
	"STRINGDATE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_TABLE
--------------------------------------------------------

  CREATE TABLE "MOHAMMAD"."USER_TABLE" 
   (	"NAME_USER" VARCHAR2(20 BYTE), 
	"EMAIL_USER" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"BIRTHDATE" DATE, 
	"ADMIN_FLAG" VARCHAR2(5 BYTE), 
	"PHONE_USER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table WORKERS
--------------------------------------------------------

  CREATE TABLE "MOHAMMAD"."WORKERS" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"PHONENUMBER" VARCHAR2(20 BYTE), 
	"WORKFLAG" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_TABLE
--------------------------------------------------------

  CREATE TABLE "MOHAMMAD"."USER_TABLE" 
   (	"NAME_USER" VARCHAR2(20 BYTE), 
	"EMAIL_USER" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"BIRTHDATE" DATE, 
	"ADMIN_FLAG" VARCHAR2(5 BYTE), 
	"PHONE_USER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "MOHAMMAD"."PRODUCT" 
   (	"PRODUCTID" NUMBER DEFAULT "MOHAMMAD"."PROUCT_ID_SEQUENCE"."NEXTVAL", 
	"PRODUCTNAME" VARCHAR2(20 BYTE), 
	"PRODUCTAREA" VARCHAR2(20 BYTE), 
	"QUANTITY" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(30 BYTE), 
	"PHONENUBMER" VARCHAR2(12 BYTE), 
	"USE_FLAG" VARCHAR2(5 BYTE), 
	"CLOTH_TYPE" VARCHAR2(10 BYTE), 
	"WELL_CLEANED" VARCHAR2(5 BYTE), 
	"CUSTOMER_EMAIL" VARCHAR2(30 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"PRICE" FLOAT(126), 
	"EMAIL_FLAG" VARCHAR2(10 BYTE), 
	"STRINGDATE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table WORKERS
--------------------------------------------------------

  CREATE TABLE "MOHAMMAD"."WORKERS" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"PHONENUMBER" VARCHAR2(20 BYTE), 
	"WORKFLAG" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into MOHAMMAD.USER_TABLE
SET DEFINE OFF;
Insert into MOHAMMAD.USER_TABLE (NAME_USER,EMAIL_USER,PASSWORD,BIRTHDATE,ADMIN_FLAG,PHONE_USER) values ('rasheed','rasheed@gmail.com','123456',to_date('08-MAR-23','DD-MON-RR'),'false','970594971026');
Insert into MOHAMMAD.USER_TABLE (NAME_USER,EMAIL_USER,PASSWORD,BIRTHDATE,ADMIN_FLAG,PHONE_USER) values ('hasan','hasan@gmail.com','123456',to_date('18-APR-23','DD-MON-RR'),'true','970599251711');
REM INSERTING into MOHAMMAD.PRODUCT
SET DEFINE OFF;
Insert into MOHAMMAD.PRODUCT (PRODUCTID,PRODUCTNAME,PRODUCTAREA,QUANTITY,ADDRESS,PHONENUBMER,USE_FLAG,CLOTH_TYPE,WELL_CLEANED,CUSTOMER_EMAIL,STATUS,PRICE,EMAIL_FLAG,STRINGDATE) values (9,'white carbet','30','2','Jenin','970594971036','true','Jacket','true','rasheed@gmail.com','complete',100,'false','20-APR-23');
Insert into MOHAMMAD.PRODUCT (PRODUCTID,PRODUCTNAME,PRODUCTAREA,QUANTITY,ADDRESS,PHONENUBMER,USE_FLAG,CLOTH_TYPE,WELL_CLEANED,CUSTOMER_EMAIL,STATUS,PRICE,EMAIL_FLAG,STRINGDATE) values (8,'black carbet','50','1','nablus','970594971025','false','null','false','rasheed@gmail.com','complete',45,'false','18-APR-23');
Insert into MOHAMMAD.PRODUCT (PRODUCTID,PRODUCTNAME,PRODUCTAREA,QUANTITY,ADDRESS,PHONENUBMER,USE_FLAG,CLOTH_TYPE,WELL_CLEANED,CUSTOMER_EMAIL,STATUS,PRICE,EMAIL_FLAG,STRINGDATE) values (43,'carbet','100','1','JENIN','970599221788','false','null','false','rasheed@gmail.com','IN_TREATMENT',45,'false','2023-04-19 11:47:55');
Insert into MOHAMMAD.PRODUCT (PRODUCTID,PRODUCTNAME,PRODUCTAREA,QUANTITY,ADDRESS,PHONENUBMER,USE_FLAG,CLOTH_TYPE,WELL_CLEANED,CUSTOMER_EMAIL,STATUS,PRICE,EMAIL_FLAG,STRINGDATE) values (44,'shirt','1','1','JENIN','970599221788','true','Shirt','true','rasheed@gmail.com','IN_TREATMENT',5.25,'false','2023-04-19 11:48:12');
REM INSERTING into MOHAMMAD.WORKERS
SET DEFINE OFF;
Insert into MOHAMMAD.WORKERS (ID,NAME,PHONENUMBER,WORKFLAG) values ('4075502322','ahmad','97059251811','false');
--------------------------------------------------------
--  DDL for Index SYS_C008317
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOHAMMAD"."SYS_C008317" ON "MOHAMMAD"."USER_TABLE" ("EMAIL_USER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008318
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOHAMMAD"."SYS_C008318" ON "MOHAMMAD"."PRODUCT" ("PRODUCTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index WORKERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOHAMMAD"."WORKERS_PK" ON "MOHAMMAD"."WORKERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008318
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOHAMMAD"."SYS_C008318" ON "MOHAMMAD"."PRODUCT" ("PRODUCTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008317
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOHAMMAD"."SYS_C008317" ON "MOHAMMAD"."USER_TABLE" ("EMAIL_USER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index WORKERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOHAMMAD"."WORKERS_PK" ON "MOHAMMAD"."WORKERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "MOHAMMAD"."PRODUCT" ADD PRIMARY KEY ("PRODUCTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_TABLE
--------------------------------------------------------

  ALTER TABLE "MOHAMMAD"."USER_TABLE" ADD PRIMARY KEY ("EMAIL_USER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WORKERS
--------------------------------------------------------

  ALTER TABLE "MOHAMMAD"."WORKERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MOHAMMAD"."WORKERS" ADD CONSTRAINT "WORKERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "MOHAMMAD"."PRODUCT" ADD FOREIGN KEY ("CUSTOMER_EMAIL")
	  REFERENCES "MOHAMMAD"."USER_TABLE" ("EMAIL_USER") ENABLE;
